export const industryOptions = [
  { value: "Banking & Finance", label: "Banking &Finance" },
  { value: "E-commerce", label: "E-commerce" },
  { value: "Food & Beverage", label: "Food & Beverage" },
  { value: "Software Development", label: "Software Development" },
  { value: "IT Services", label: "IT Services" },
  { value: "Big Data", label: "Big Data" },
  { value: "Cybersecurity", label: "Cybersecurity" },
  { value: "Fintech", label: "Fintech" },
  { value: "Education", label: "Education" },
  { value: "Edtech", label: "Edtech" },
  { value: "AI/Machine Learning", label: "AI/Machine Learning" },
  { value: "Manufacturing", label: "Manufacturing" },
  { value: "Construction", label: "Construction" },
  { value: "Pharmaceuticals", label: "Pharmaceuticals" },
  { value: "Medical Devices", label: "Medical Devices" },
  { value: "Biotechnology", label: "Biotechnology" },
  { value: "Healthcare", label: "Healthcare" },
  { value: "Healthtech", label: "Healthtech" },
  { value: "Entertainment", label: "Entertainment" },
  { value: "Renewable Energy", label: "Renewable Energy" },
  { value: "Transportation", label: "Transportation" },
  { value: "Logistics", label: "Logistics" },
  { value: "Fashion", label: "Fashion" },
  { value: "Real Estate", label: "Real Estate" },
  { value: "Travel & Hospitality", label: "Travel & Hospitality" },
  { value: "Automotive", label: "Automotive" },
  { value: "Agriculture & Agtech", label: "Agriculture & Agtech" },
  { value: "Marketing & Advertising", label: "Marketing & Advertising" },
  { value: "Telecommunications", label: "Telecommunications" },
  { value: "Environmental Services", label: "Environmental Services" },
  { value: "Fitness & Wellness", label: "Fitness & Wellness" },
];

export const sizeOptions = [
  { value: "1-5", label: "1-5 employees" },
  { value: "5-10", label: "5-10 employees" },
  { value: "10-50", label: "10-50 employees" },
  { value: "50-100", label: "50-100 employees" },
  { value: "101-150", label: "101-150 employees" },
  { value: "151-200", label: "151-200 employees" },
  { value: "201-300", label: "201-300 employees" },
  { value: "301-400", label: "301-400 employees" },
  { value: "401-500", label: "401-500 employees" },
  { value: "500+", label: "500+ employees" },
];
